import { StyleSheet } from "react-native";

export const stylesDefault = StyleSheet.create({
  ViewBody: {
    paddingHorizontal: 20,
    width: "100%",
    height: "auto",
  },
  RedViewHeaderContainer: {
    backgroundColor: "red",
    height: 120,
    width: "100%",
    paddingHorizontal: 30,

    justifyContent: "space-between",
    borderBottomLeftRadius: 40,
    flexDirection: "row",
    alignItems: "center",
  },
  RedViewFirstText: {
    color: "white",
    fontWeight: "800",
    fontSize: 18,
  },
  RedViewSecondText: {
    color: "white",
    fontWeight: "800",
    marginLeft: 5,
    fontSize: 18,
  },
  SmallText_Black_18_600: {
    color: "black",
    fontWeight: "600",
    fontSize: 18,
  },
  SmallText_Black_30_600: {
    color: "black",
    fontWeight: "600",
    fontSize: 30,
  },
  View_Row_HSpaceBetween_VCenter_W100: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    alignItems: "center",
  },
  View_Row_VCenter_W24_H12: {
    width: 24,
    alignItems: "center",
    height: 12,
  },
  View_HCenter_W30_H30_BorderRadius50_BackgroundColor_85d151: {
    backgroundColor: "#85d151",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    height: 30,
    width: 30,
  },
  Image_W100_H100_Tint_Red: {
    width: "100%",
    height: "100%",
    tintColor: "rgba(255, 0, 0, 0.65)",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    top: 0,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 5,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: "90%",
    height: 500,
  },
  joinButton: {
    backgroundColor: "#85d151",
    marginTop: 30,
    width: 150,
    height: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#85d151",
    gap: 10,
  },
  joinText: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "bold",
  },
  modalHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalHeaderText: {
    fontWeight: '700',
    fontSize: 26,
    color: 'red',
  },
  modalText: {
    fontWeight: '400',
    fontSize: 17,
    color: 'black',
    maxWidth: '90%',
    marginBottom: 15,
  },
  warningContainer: {
    width: '100%',
    marginBottom: 15,
  },
  warningBox: {
    backgroundColor: 'red',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  warningText: {
    color: 'white',
    marginLeft: 10,
  },
  codeInputContainer: {
    borderColor: 'black',
    borderWidth: 2,
    width: '100%',
    height: 60,
    borderRadius: 50,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  codeInput: {
    opacity: 0,
    width: '100%',
    position: 'absolute',
    height: 80,
    padding: 0,
    margin: 0,
    backgroundColor: 'black',
    zIndex: 3,
  },
  codeDigit: {
    borderBottomColor: 'black',
    borderBottomWidth: 4,
    width: 34,
    alignItems: 'center',
  },
  codeDigitText: {
    fontSize: 24,
    bottom: 0,
    fontWeight: '700',
  },
  lockIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendAgainContainer: {
    width: '100%',
    alignItems: 'center',
  },
  sendAgainButton: {
    backgroundColor: '#85d151',
    width: 'auto',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#85d151',
    paddingHorizontal: 20,
  },
  sendAgainText: {
    fontSize: 16,
    color: 'grey',
    borderBottomColor: 'grey',
    borderBottomWidth: 2,
  },
  confirmButton: {
    backgroundColor: '#85d151',
    marginTop: 30,
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#85d151',
    paddingHorizontal: 20,
  },
  confirmButtonText: {
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
    marginRight: 10,
  },
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#F3F3F3",
  },
  insideContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  confirmTitle: {
    fontWeight: "800",
    fontSize: 30,
    color: "#85D151",
    textAlign: "center",
    marginVertical: 20,
  },
  confirmText: {
    fontWeight: "500",
    fontSize: 20,
    color: "black",
    textAlign: "center",
    marginBottom: 20,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  formContainer: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
  },
  formTitle: {
    color: "red",
    fontWeight: "800",
    fontSize: 29,
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    borderRadius: 50,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "grey",
    padding: 5,
    paddingLeft: 30,
    height: 50,
  },
  pickerContainer: {
    borderRadius: 50,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "grey",
    padding: 5,
    height: 50,
  },
  picker: {
    bottom: 10,
  },
  textArea: {
    borderTopStartRadius: 20,
    borderTopEndRadius: 20,
    borderBottomStartRadius: 20,
    borderBottomEndRadius: 20,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "grey",
    padding: 5,
    paddingLeft: 8,
    height: 180,
  },
  button: {
    backgroundColor: "red",
    borderRadius: 10,
    paddingVertical: 12,
    marginTop: 20,
  },
  buttonText: {
    fontSize: 18,
    color: "white",
    fontWeight: "700",
    textAlign: "center",
  },
  
  containerRed: {
    backgroundColor: "red",
    padding: 20,
    marginBottom: 10,
  },
  whiteText: {
    color: "white",
    fontWeight: "800",
    fontSize: 18,
  },
  body: {
    padding: 20,
  },
  menu: {
    marginBottom: 20,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F3F3",
  },
  menuItemText: {
    fontSize: 16,
    fontWeight: "600",
  },
  iconContainer: {
    backgroundColor: "#85d151",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 50,
    height: 30,
    width: 30,
  },
  answerContainer: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#F3F3F3",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  answer: {
    fontSize: 14,
    color: "black",
  },
  backContainer: {
    position: "absolute",
    top: 20,
    left: 20,
    zIndex: 1,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 10,
    textAlign: "center",
  },
  inputContainer: {
    width: "100%",
    marginBottom: 20,
  },
  finishTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  contactContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
  },
  contactTextBlack: {
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 10,
  },
  contactTextRed: {
    fontSize: 16,
    color: "red",
    fontWeight: "bold",
    marginLeft: 5,
  },
  image: {
    width: 200,
    height: 100,
    resizeMode: "contain",
    marginTop: 20,
  },
  counter: {
    fontSize: 18,
  },
  header: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bottomContainer: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  stepContainer: {
    flexDirection: "column",
    justifyContent: "space-between",
    height: "auto",
  },
  infoContainer: {
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: "auto",
    padding: 20,
    backgroundColor: "white",
    borderRadius: 20,
    bottom: 30,
  },
  
  SmallText_Black_600: {
    color: "black",
    fontWeight: "600",
    fontSize: 18,
  },

  scrollView: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 20,
    marginTop: -10,
  },
  inputContainerLogin: {
    paddingHorizontal: 20,
    width: "100%",
    marginBottom: 20,
  },
  loginButton: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#85d151",
    marginTop: 10,
    width: "100%",
    height: 50,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
    flexDirection: "row",
  },
  loginText: {
    fontSize: 18,
    color: "#85d151",
    fontWeight: "bold",
  },
  headerProfile: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  touchableBody: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  iconView: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#85d151",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 15,
  },
  headerProfileText: {
    color: "red",
    fontSize: 24,
    fontWeight: "600",
  },
  headerProfileButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  profileSettingsText: {
    fontSize: 20,
  },
  currencySymbol: {
    fontSize: 20,
    fontWeight: "700",
  },
  inputAmount: {
    width: "100%",
    flex: 1,
    height: 50,
    fontSize: 20,
  },
  minValueText: {
    fontSize: 14,
    fontWeight: "400",
  },
  transferInfoContainer: {
    borderWidth: 1,
    borderColor: "black",
    height: 200,
    width: "95%",
    borderRadius: 12,
    padding: 20,
  },
  transferInfoTitle: {
    fontSize: 22,
    fontWeight: "600",
    marginTop: 10,
  },
  transferInfoSubtitle: {
    fontSize: 14,
    color: "#a9a9a9",
    fontWeight: "600",
  },
  successContainer: {
    flexDirection: "row",
    gap: 14,
  },
  successButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  receiptContainer: {
    borderWidth: 1,
    borderColor: "#a9a9a9",
    height: 200,
    width: "95%",
    borderRadius: 12,
    padding: 20,
  },
  receiptText: {
    fontSize: 14,
    color: "#a9a9a9",
    fontWeight: "600",
  },
  shareContainer: {
    flexDirection: "row",
    gap: 10,
  },
  shareText: {
    fontSize: 16,
    fontWeight: "600",
    color: "red",
    textDecorationColor: "red",
    textDecorationLine: "underline",
  },
  errorContainer: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  errorButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  errorText: {
    fontSize: 20,
    fontWeight: "600",
  },
  errorTitle: {
    fontWeight: "600",
    fontSize: 20,
  },
  errorRule: {},
  processingContainer: {
    flexDirection: "row",
    gap: 14,
  },
  processingButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  processingText: {
    fontWeight: "600",
    fontSize: 20,
  },
  processingDetail: {},
  warningHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  warningMessage: {
    paddingRight: 10,
  },
  viewContainer: {
    marginTop: -50,
    flexDirection: "column",
    padding: 20,
    width: "100%",
    height: "100%",
  },
  viewInnerContainer: {
    flexDirection: "column",
    backgroundColor: "white",
    width: "100%",
    height: "auto",
    borderRadius: 10,
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollViewFull: {
    width: "100%",
    height: "auto",
  },
  headerText: {
    alignSelf: "center",
    fontSize: 24,
    color: "red",
    fontWeight: "600",
    marginBottom: 30,
  },
  menuItemTextBold: {
    fontWeight: "600",
    fontSize: 20,
  },
  webviewContainer: {
    backgroundColor: "white",
    padding: 10,
    bottom: 30,
    borderRadius: 20,
    marginHorizontal: 20,
  },
  webview: {
    height: '100%',
    width: '100%',
  },
});
